#!/bin/bash

# Another rewrite. This one pretty much just gets the URL to the point where Youtube-dl can do its magic. Because it can.

# If there is a separate episode list, put each number in ~/.config/conan-dl/eplist.list separated by spaces or newlines.

source ~/.config/conan-dl/conan-dl.conf
eplist=$(
    seq $firstep $lastep ||
       cat ~/.config/conan-dl/eplist.list
    )
mkdir -p $outputdir
cd $outputdir
animegg=$(
    echo $anime |
    sed 's/ /-/g'
)
fname=$(
    echo "$anime /" |
    awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1' |
    sed 's/[a-z]//g;s/ //g;s/\//ep/g'
)
find-rawstream () {
    curl $streamurl |
    sed -n -E '
        /^[[:space:]]*<a href="#" rel="100"/{
        s/.*data-video="([^"]*)".*/https:\1/p
        q
        }'
}
for ep in $eplist
do
streamurl="https://$streamsite/$animegg-episode-$ep"

youtube-dl $(find-rawstream)
mv *\ $ep-loadserver.mp4 $fname$ep.mp4
done
#cd
