#!/usr/bin/env bash

# A complete rewrite of conan-dl(archived here as cdl-curl) and improving all inefficiencis of cdl-wget: a program which scrapes anime from basic non-JS sites.
# This version relies on GNU Wget as well as cURL, because while they happen to be somewhat similar, they do have different uses. For instance: wget has a far superior progress bar.
#
# One day I may also try to replace all awk commands with sed commands for a similar reason.
# But that time is not now. Anyway, read the code and read the config file and check the README.
# Aight let's get down to it.

# preliminary check to make sure stuff works
deps="bash sed awk curl wget cat grep mkdir"
for dep in $deps
do
	[[ `which $dep 2>/dev/null` ]] && echo "Dependency $dep satisfied!" || echo "Error: Dependency $dep not satisfied! Please install it and continue."
done

source $HOME/.config/conan-dl/conan-dl.conf
mkdir -p $outputdir

#FUNCTIONS (global)
animegg=$(
	echo $anime |
	sed 's/ /-/g'
)
fname=$(
	echo "$anime /" |
	awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1' |
	sed 's/[a-z]//g;s/ //g;s/\//ep/g'
)
finalurl() {
	curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- "$@";
}
wget-stream () {
	wget -q $streamurl -O $tmpdir/cdl.tmp
}
find-dlhub () {
	cat $tmpdir/cdl.tmp |
	grep $mirrorfz1 |
	grep ownload |
	awk '{print $3}' |
	sed 's/href=//g;s/"//g'
}
wget-dlhub () {
	wget -q $dlhub -O $tmpdir/cdl.tmp
}
find-mirrorurl () {
	cat $tmpdir/cdl.tmp |
	grep -B 2 "$resolution" |
	grep "$mirrorfz2" |
	awk '{print $1}' |
	sed 's/href=//g' |
	sed 's/"//g'
}
wget-mirrorurl () {
	wget -q --show-progress $mirrorurl -O $outputdir/$fname$ep.mp4
}
streamsite=$(
	finalurl $streamsite
)
#everything is inside of this FOR function now. I'm sorry.
for ep in $(seq $firstep $lastep)
do
streamurl=$(
	echo $streamsite/$animegg-episode-$ep
)
wget-stream
dlhub=$(find-dlhub)
wget-dlhub
mirrorurl=$(find-mirrorurl)
wget-mirrorurl
done

#######BEGIN HYBRID CONAN-DL, WITH THE CURL BITS INTACT#############


for ep in $(seq $firstep $lastep)
do
	dlurl=$(curl -s $(
		curl -s `finalurl gogoanime.ai`$animegg-episode-$ep |
		grep gogo-play | grep ownload | awk '{print $3}' |
		sed 's/href=//;s/"//g'
	) |
	grep -B 1 $res | grep "mp4" -B 1 | grep href | awk '{print $1}' | sed 's/href=//;s/"//g'
)
wget -nv -O "$outputdir/DCep$ep" $dlurl
done
