#!/bin/sh

# Declare{
startingdir="$PWD"
tmpdir="${TMPDIR:-/tmp}"
refresh="0.5"
watch="no"
menu="fzf"#}

# Define
is_integer () {
    case "${1#[+-]}" in
        (*[!0123456789]*) return 1 ;;
        ('')              return 1 ;;
        (*)               return 0 ;;
    esac
}
search_anime () {
    # USAGE: search_anime "$search" where $search is the approx anime name
    search=$1
    curl -s "https://$streamsite//search.html" \
        -G \
        -d "keyword=$search" |
    sed -n -E 's_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p' |
    $menu
    # get_animegg is no longer necessary. This does it all and spits out animegg.
}

# Process

# Print
